# Generated by Django 5.1.6 on 2025-04-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PC', 'PC'), ('laptop', 'Laptop'), ('gaming_laptop', 'Laptop Gaming'), ('office_laptop', 'Laptop Văn Phòng'), ('accessories', 'Phụ kiện máy tính'), ('DWUJA', 'DWUJA')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
